use strict;
use warnings;
use Test::More;
use Imager::Test qw/ is_image /;
use File::Spec;
use File::Basename;

use Imager::Heatmap;

my $hmap = Imager::Heatmap->new(
    xsize  => 1000,
    ysize  => 1000,
    xsigma => 20.0,
    ysigma => 20.0,
);

my $path = File::Spec->catfile(File::Basename::dirname(__FILE__), 'resources', 'sample.tsv');
open my $fh, '<', $path or die "Can't open file $path: $!";

my @array;
while (my $line = <$fh>) {
    chomp $line;
    push @array, [ split /\s/, $line ];
}

my $fetch_method = sub {
    defined(my $line = <$fh>) or return;
    chomp $line;
    return split /\s/, $line
};

my $matrix_arrsrc = $hmap->insert_datas(@array);

seek $fh, 0, 0;
@{ $hmap->matrix } = ();
$hmap->insert_datas(@array[0..$#array/2]);
my $matrix_splitsrc = $hmap->insert_datas(@array[$#array/2+1..$#array]);

is_deeply $matrix_arrsrc, $matrix_splitsrc, "Two matrix generated by single source and splitted source should be same";

done_testing;
